### ISSUE TITLE
PHP 5.4

### ISSUE THREAD

**Issue by peter-mw** [GrahamCampbell/Laravel-Security#23]
Hello Graham, 

I am trying to use your class under php 5.4, but i see in the composer.json file that you require php 5.5 

Is php 5.5 really necessary as requirement? 

I cannot install the lib with php 5.4. It gives me the following error on `composer install`

```
  Problem 1
    - graham-campbell/security v3.1.0 requires php >=5.5.9 -> your PHP version (5.4.22) does not satisfy that requirement.
    - graham-campbell/security 3.1.x-dev requires php >=5.5.9 -> your PHP version (5.4.22) does not satisfy that requirement.
    - Installation request for graham-campbell/security ~3.1 -> satisfiable by graham-campbell/security[3.1.x-dev, v3.1.0].
```

I manually downloaded the Security.php file from https://github.com/GrahamCampbell/Laravel-Security/blob/master/src/Security.php and its working fine on php 5.4

If php 5.5 is not really required, can you reduce the version to 5.4, so i can include this as dependency in my [composer.json](https://github.com/microweber/microweber/blob/1.0.2/composer.json) 

Cheers :)

**Comment by GrahamCampbell** [comment]
I don't intend to support php 5.4 as it's no longer receiving bug fixes from the php team.

**Comment by GrahamCampbell** [comment]
If you need php 5.4 support, 2.x and 3.0.x of this package still support php 5.4.
