### ISSUE TITLE
Question/Enhancement: Allow NULL value in Security::process()

### ISSUE THREAD

**Issue by lftbrts** [GrahamCampbell/Laravel-Security#32]
```Argument 1 passed to GrahamCampbellSecuritySecurity::process() must be of the type string, null given, called in /var/www/umb2b/vendor/graham-campbell/security/src/Security.php on line 82```
The middleware `Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull` (Laravel 5.5) converts empty strings to NULL values. This forces you to define (sometimes messy) exceptions using `Request::except()` in order to use `Security::*`.
Is there a need for the type-hint `string` in process()?

**Comment by GrahamCampbell** [comment]
Yes, you may only pass strings or arrays of strings to the clean function. If you want to exclude nulls, do an array_filter in your code first.

**Comment by GrahamCampbell** [comment]
Where are you calling the security class please, for some context?

**Comment by lftbrts** [comment]
I'm using the security service in a repository where a form-request object comes in (nullable values are allowed in validation rules) and where I get my data for cleaning. I could use BInput in that context; BInput filters out null values before using Security, but that is something I don't want. Yes, it is a question of software architecture, also not a drama to fulfil the requirements to use Security.
