### ISSUE TITLE
using percentages in text breaks the clean method

### ISSUE THREAD

**Issue by Zae** [GrahamCampbell/Laravel-Security#36]
Hi Graham,

I've noticed that something seems to be broken with the parsing of % signs in text. I think this bug was introduced the last time you synced your package with codeIgniter.

Input: 100% received
Expected: 100% received
Actual:  100%received

Input: 100% better
Expected: 100% better
Actual: 100¾tter

It seems that because on line 103 spaces are removed from the input when a % sign is present in the string, 100% better => the urlDecodeSpaces method receives % be, and this gets converted to %be, and then converted by rawurldecode to ¾

I'm not sure what this part of the code is actually supposed to be doing so sadly I can't think of any way to fix it short of commenting it out.

**Comment by Zae** [comment]
Found the same issue in the CI issue tracker, looks like they closed the issue without a fix: https://github.com/bcit-ci/CodeIgniter/issues/5125

**Comment by GrahamCampbell** [comment]
Going to have to mark this as a no-fix then. Thanks for looking into it though.

This package will keep in-sync with whatever CodeIgniter does.

**Comment by Zae** [comment]
Hey Graham,

I understand, I'll try to take it up with codeigniter then.

Op 6 mrt. 2018 19:54 schreef "Graham Campbell" <notifications@github.com>:
