### ISSUE TITLE
Package usage

### ISSUE THREAD

**Issue by Nagraj137** [GrahamCampbell/Laravel-Security#39]
Hi,

I don't understand how to use this package. i have installed, but i don't know where to use security facade, website link not working https://gjcampbell.co.uk/

Please guide me how to use this package.

Thanks,

**Comment by GrahamCampbell** [comment]
Hi there. The readme describes the usage, although is missing a clear code example.

This package provides essentially one method `Security::clean`. Just pass some HTML to it, and it will remove any executable code from it. This is useful if you don't want to escape the HTML, but also don't want XSS attacks.

**Comment by GrahamCampbell** [comment]
There are some examples here (that don't use the facade) https://github.com/GrahamCampbell/Security-Core/blob/master/tests/SecurityTest.php.
