### ISSUE TITLE
please add security clickjack

### ISSUE THREAD

**Issue by vahidalvandi** [GrahamCampbell/Laravel-Security#41]
hey
i found https://github.com/getspooky/Laravel-Mitnick it have multi middleware and contain multi security like clickjack

**Comment by GrahamCampbell** [comment]
That'd definitely be out of scope of this package. This package is for sanatizing input. For headers, I'd actually recommend you get your load balancer or Nginx to set them on the way out. This is going to be the fastest and actually, safest way to do it, so your static files get the headers too. That package you linked to is flawed in that sense. :)

**Comment by GrahamCampbell** [comment]
Here's an example Nginx file of mine (with truncated CSP header line):

![image](https://user-images.githubusercontent.com/2829600/87326393-935f0e00-c52a-11ea-9159-298cfaa3c2b5.png)

**Comment by vahidalvandi** [comment]
> Here's an example Nginx file of mine (with truncated CSP header line):
> 
> ![image](https://user-images.githubusercontent.com/2829600/87326393-935f0e00-c52a-11ea-9159-298cfaa3c2b5.png)

this sample must add in ngnix or apache ??

how i can add this with laravel manually ?

**Comment by GrahamCampbell** [comment]
It's not possible to set these headers in Laravel because they would only be set for requests that actually hit Laravel. All your static files would not have the headers set. If that doesn't matter for you, then you can just set those headers using a simple Laravel middleware. https://laravel.com/docs/7.x/middleware, https://laracasts.com/discuss/channels/laravel/set-header-in-request-middleware?page=1#reply=155571

**Comment by vahidalvandi** [comment]
thank you

**Comment by vahidalvandi** [comment]
i add this Middleware to web gorup  do this safe and ok ???


```
    public function handle(Request $request, Closure $next)
    {

        $response = $next($request);

//add from https://github.com/getspooky/Laravel-Mitnick/tree/master/src/Security
        
        $response->header('X-Frame-Options','deny');
        $response->header('Cache-Control','no-store, no-cache, must-revalidate, max-age=0, s-maxage=0');
        $response->header('X-DNS-Prefetch-Control', 'off');
        $response->header('Strict-Transport-Security' , 'max-age=5184000,preload');
        $response->header('X-Content-Type-Options' , 'nosniff');
        header_remove("X-Powered-By");

        return $response;
    }

```
