### ISSUE TITLE
please show example of usage

### ISSUE THREAD

**Issue by vahidalvandi** [GrahamCampbell/Laravel-Security#42]
dear @GrahamCampbell  i install package with composer , do it automatically add xss security in my app ? or need aditional work ?
`composer require graham-campbell/security`

**Comment by GrahamCampbell** [comment]
This package simply provides a facade that you can pass an HTML string through to stop XSS. This documented at https://github.com/GrahamCampbell/Laravel-Security#usage. If you're even in doubt over what a package does, check https://github.com/GrahamCampbell/Laravel-Security/tree/master/src. There are only two classes. ;)

**Comment by vahidalvandi** [comment]
Ok . I dont know what html need xss clean ! .
I have home page or contact us form . Where need use xss clean ?

**Comment by GrahamCampbell** [comment]
You would only wanna clean it if you planned on rendering it as HTML later. Say if you allow a user to post a comment on your website using html syntax, and you wanted to render it, but not have them inject JS.

**Comment by vahidalvandi** [comment]
If i clean all input with xss in middlware is ok way ?

**Comment by GrahamCampbell** [comment]
You don't wanna just blanket do this, in general.
