### ISSUE TITLE
add removeEvilHtmlTags

### ISSUE THREAD

**Issue by b1nj** [GrahamCampbell/Laravel-Security#43]
Can you add method removeEvilHtmlTags ?

It's to authorize Iframe like Youtube.

``
$antiXss->removeEvilHtmlTags(array('iframe'));
``

**Comment by GrahamCampbell** [comment]
You can specify the evil tags you want to have stripped in the config file: https://github.com/GrahamCampbell/Laravel-Security/blob/8.0/config/security.php#L26. :)

**Comment by GrahamCampbell** [comment]
There's some information on the README about configuration: https://github.com/GrahamCampbell/Laravel-Security#configuration.

**Comment by b1nj** [comment]
The config evil is just for attributes, not for tags.

https://github.com/GrahamCampbell/Security-Core/blob/4fb44d9d0949ce0bb3b6ee42dc672bac646f9c16/src/Security.php#L63

**Comment by GrahamCampbell** [comment]
This will be implemented in v9.0.0. :)

**Comment by b1nj** [comment]
Perfect. Merci
